services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - 1337:1337
    volumes:
      - ./:/opt/app
    command: yarn develop
